version: '3.8'

services:
  ehmi:
    image: andreclerigo/av-ehmi:latest
    container_name: ehmi-app
    restart: unless-stopped
    ports:
      - "5003:5003"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003"]
      interval: 30s
      timeout: 10s
      retries: 3
